version: "3.1"

services:
  nms:
    image: 'ghcr.io/droneit-es/node-media-server:latest'
    container_name: nms
    restart: unless-stopped
    secrets:
      - apikey
      - playerkey
    volumes:
      - "./mnt/user/appdata/nginx/letsencrypt/:/etc/letsencrypt"
    ports:
      - 1935:1935
      - 8000:8000
      - 8443:8443
    networks:
      lsio: {}

  nginx:
   image: 'jc21/nginx-proxy-manager:latest'
   restart: unless-stopped
   ports:
    - '80:80' #Public HTTP Port
    - '443:443' #Public HTTPS Port
    - '81:81' #Admin Web Port
   volumes:
    - "./mnt/user/appdata/nginx/data:/data"
    - "./mnt/user/appdata/nginx/letsencrypt:/etc/letsencrypt"
   networks:
    lsio: {}
 

secrets:
  apikey:
    file: .apikey
  playerkey:
    file: .playerkey


networks:
  lsio:
    driver: bridge
    name: lsio

